<a href="https://colab.research.google.com/github/SabinaZet/olx-nieruchomosci/blob/main/olx_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Źródła

- [RealPython Pythonic Data Cleaning With pandas and NumPy](https://realpython.com/python-data-cleaning-numpy-pandas/)

# Set up GitHub connection and localisation

In [2]:
!git clone https://github.com/SabinaZet/olx-nieruchomosci.git

Cloning into 'olx-nieruchomosci'...
remote: Enumerating objects: 125, done.
remote: Counting objects: 100% (125/125), done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 125 (delta 76), reused 117 (delta 70), pack-reused 0 (from 0)
Receiving objects: 100% (125/125), 26.50 KiB | 8.83 MiB/s, done.
Resolving deltas: 100% (76/76), done.

In [3]:
#add your modules to Colab sys
import sys
sys.path.append("/content/olx-nieruchomosci")  # dodaj główny folder

Change working directory witch magic command (%) - ! doesn't work in Colab

In [4]:
%cd /content/olx-nieruchomosci

/content/olx-nieruchomosci

Update connection:

In [19]:
!git fetch origin

remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 5 (delta 2), reused 5 (delta 2), pack-reused 0 (from 0)
Unpacking objects: 100% (5/5), 2.86 KiB | 1.43 MiB/s, done.
From https://github.com/SabinaZet/olx-nieruchomosci
   50d5c37..ea0be05  main       -> origin/main

Check for changes and update if needed:

In [20]:
!git status

On branch main
Your branch is behind 'origin/main' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working tree clean

In [21]:
!git pull

Updating 50d5c37..ea0be05
Fast-forward
 main.py           |  22 +++--
 pipeline/clean.py | 269 +++++++++++++++++++++++++++++++++++++++++++++++++-----
 2 files changed, 263 insertions(+), 28 deletions(-)

# Normalizing Data Frames

## Get and pre-clean the data from OLX

In [7]:
from pipeline import paginate, normalized_data
import pipeline.clean as pc
import pandas as pd

#list of dicts with scraped pages data,metadata and links
pages = paginate()

#dict with data split into categories and DFs as values
data_categories = normalized_data(pages)

#print df.info() and df.head(2) for all dfs
#pc.key_info(data_categories)

#delete NaN columns and duplicate id from all dfs and check
dfs_cl = pc.clean_nan_df(data_categories)
dfs_cl = pc.deduplicate(dfs_cl)
pc.key_info(dfs_cl)

#print df name and each column with the number of unique values
pc.check_data(dfs_cl)

No 'next' link

data_location
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 0 to 1299
Data columns (total 18 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   id                               1279 non-null   int64
 1   isGpsrAvailable                  1279 non-null   bool
 2   location.city.id                 1279 non-null   int64
 3   location.city.name               1279 non-null   object
 4   location.city.normalized_name    1279 non-null   object
 5   location.city._nodeId            52 non-null     object
 6   location.district.id             522 non-null    float64
 7   location.district.name           522 non-null    object
 8   location.district._nodeId        19 non-null     object
 9   location.region.id               1279 non-null   int64
 10  location.region.name             1279 non-null   object
 11  location.region.normalized_name  1279 non-null   object
 12  location.region._nodeId          52 non-null     object
 13  map.lat                          1279 non-null   float64
 14  map.lon                          1279 non-null   float64
 15  map.radius                       1279 non-null   int64
 16  map.show_detailed                1279 non-null   bool
 17  map.zoom                         1279 non-null   int64
dtypes: bool(2), float64(3), int64(5), object(8)
memory usage: 172.4+ KB
None
           id  isGpsrAvailable  location.city.id location.city.name  \
0  1050124482            False             17871           Warszawa
1  1035545057            False            102641          Niesłabin

  location.city.normalized_name location.city._nodeId  location.district.id  \
0                      warszawa      Y2l0eToxNzg3MQ==                 353.0
1                     nieslabin      Y2l0eToxMDI2NDE=                   NaN

  location.district.name location.district._nodeId  location.region.id  \
0                Mokotów          ZGlzdHJpY3Q6MzUz                   2
1                    NaN                       NaN                   1

  location.region.name location.region.normalized_name  \
0          Mazowieckie                     mazowieckie
1        Wielkopolskie                   wielkopolskie

  location.region._nodeId   map.lat   map.lon  map.radius  map.show_detailed  \
0            cmVnaW9uOjI=  52.19282  21.03232           7              False
1            cmVnaW9uOjE=  52.16511  17.01334           0               True

   map.zoom
0        13
1        14

data_timing
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 0 to 1299
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   1279 non-null   int64
 1   last_refresh_time    1279 non-null   object
 2   created_time         1279 non-null   object
 3   omnibus_pushup_time  622 non-null    object
 4   valid_to_time        1279 non-null   object
dtypes: int64(1), object(4)
memory usage: 60.0+ KB
None
           id          last_refresh_time               created_time  \
0  1050124482  2026-02-06T06:38:01+01:00  2026-01-18T11:16:21+01:00
1  1035545057  2026-02-06T16:33:40+01:00  2025-10-30T18:18:37+01:00

         omnibus_pushup_time              valid_to_time
0  2026-02-06T06:38:01+01:00  2026-02-17T11:16:21+01:00
1  2026-02-06T16:33:40+01:00  2026-02-09T16:37:59+01:00

data_category
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 0 to 1299
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                1279 non-null   int64
 1   offer_type        1279 non-null   object
 2   category.id       1279 non-null   int64
 3   category.type     1279 non-null   object
 4   category._nodeId  52 non-null     object
dtypes: int64(2), object(3)
memory usage: 60.0+ KB
None
           id offer_type  category.id category.type  category._nodeId
0  1050124482      offer           11   real_estate  Y2F0ZWdvcnk6MTE=
1  1035545057      offer           18   real_estate  Y2F0ZWdvcnk6MTg=

data_business
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 0 to 1299
Data columns (total 27 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                1279 non-null   int64
 1   business                          1279 non-null   bool
 2   protect_phone                     1099 non-null   object
 3   contact.chat                      1279 non-null   bool
 4   contact.name                      1279 non-null   object
 5   contact.negotiation               1279 non-null   bool
 6   contact.phone                     1279 non-null   bool
 7   shop.subdomain                    49 non-null     object
 8   user.id                           1279 non-null   int64
 9   user.uuid                         1279 non-null   object
 10  user._nodeId                      52 non-null     object
 11  user.about                        1279 non-null   object
 12  user.b2c_business_page            1279 non-null   bool
 13  user.banner_desktop               1279 non-null   object
 14  user.banner_mobile                1279 non-null   object
 15  user.company_name                 1279 non-null   object
 16  user.created                      1279 non-null   object
 17  user.is_online                    1279 non-null   bool
 18  user.last_seen                    1279 non-null   object
 19  user.logo_ad_page                 41 non-null     object
 20  user.name                         1279 non-null   object
 21  user.other_ads_enabled            1279 non-null   bool
 22  user.photo                        147 non-null    object
 23  user.social_network_account_type  289 non-null    object
 24  user.verification.status          52 non-null     object
 25  partner.code                      241 non-null    object
 26  contact.courier                   1227 non-null   object
dtypes: bool(7), int64(2), object(18)
memory usage: 218.6+ KB
None
           id  business protect_phone  contact.chat      contact.name  \
0  1050124482     False          True          True            Wojtek
1  1035545057      True          True          True  HOME4ME Sp z o o

   contact.negotiation  contact.phone shop.subdomain     user.id  \
0                False           True           None  1497179207
1                False           True           None    21117567

                              user.uuid  ... user.is_online  \
0  9faf5def-6fce-48f9-b358-6f7166b38c43  ...          False
1  ffce0e06-25f9-4d4f-9a59-ae1477b57dce  ...           True

              user.last_seen  user.logo_ad_page         user.name  \
0  2026-02-05T20:09:59+01:00               None           woj1492
1  2026-02-08T00:13:31+01:00               None  HOME4ME Sp z o o

  user.other_ads_enabled user.photo user.social_network_account_type  \
0                   True       None                             None
1                   True       None                             None

   user.verification.status partner.code contact.courier
0                      none          NaN             NaN
1                      none    otodom_pl             NaN

[2 rows x 27 columns]

data_offer
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 0 to 1299
Data columns (total 18 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   id                               1279 non-null   int64
 1   _nodeId                          52 non-null     object
 2   title                            1279 non-null   object
 3   status                           1279 non-null   object
 4   url                              1279 non-null   object
 5   description                      1279 non-null   object
 6   external_url                     241 non-null    object
 7   location.city.id                 1279 non-null   int64
 8   location.city.name               1279 non-null   object
 9   location.city.normalized_name    1279 non-null   object
 10  location.city._nodeId            52 non-null     object
 11  location.district.id             522 non-null    float64
 12  location.district.name           522 non-null    object
 13  location.district._nodeId        19 non-null     object
 14  location.region.id               1279 non-null   int64
 15  location.region.name             1279 non-null   object
 16  location.region.normalized_name  1279 non-null   object
 17  location.region._nodeId          52 non-null     object
dtypes: float64(1), int64(3), object(14)
memory usage: 189.9+ KB
None
           id                           _nodeId  \
0  1050124482  bGVnYWN5QWR2ZXJ0OjEwNTAxMjQ0ODI=
1  1035545057  bGVnYWN5QWR2ZXJ0OjEwMzU1NDUwNTc=

                                               title  status  \
0  Komfortowy pokój z balkonem, Mokotów, obok met...  active
1  Piękna rezydencja przy lesie w stylu Vastu w s...  active

                                                 url  \
0  https://www.olx.pl/d/oferta/komfortowy-pokoj-z...
1  https://www.olx.pl/d/oferta/piekna-rezydencja-...

                                         description  \
0  English description bellow!<br />\n<br />\nDo ...
1  <p></p><p>Nieruchomość położona jest pośród pó...

                                        external_url  location.city.id  \
0                                               None             17871
1  https://www.otodom.pl/pl/oferta/piekna-rezyden...            102641

  location.city.name location.city.normalized_name location.city._nodeId  \
0           Warszawa                      warszawa      Y2l0eToxNzg3MQ==
1          Niesłabin                     nieslabin      Y2l0eToxMDI2NDE=

   location.district.id location.district.name location.district._nodeId  \
0                 353.0                Mokotów          ZGlzdHJpY3Q6MzUz
1                   NaN                    NaN                       NaN

   location.region.id location.region.name location.region.normalized_name  \
0                   2          Mazowieckie                     mazowieckie
1                   1        Wielkopolskie                   wielkopolskie

  location.region._nodeId
0            cmVnaW9uOjI=
1            cmVnaW9uOjE=

data_promoted
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 0 to 1299
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         1279 non-null   int64
 1   promotion.highlighted      1279 non-null   bool
 2   promotion.top_ad           1279 non-null   bool
 3   promotion.options          1279 non-null   object
 4   promotion.premium_ad_page  1279 non-null   bool
 5   promotion.urgent           1279 non-null   bool
 6   promotion.b2c_ad_page      1279 non-null   bool
dtypes: bool(5), int64(1), object(1)
memory usage: 36.2+ KB
None
           id  promotion.highlighted  promotion.top_ad promotion.options  \
0  1050124482                   True              True  [bundle_optimum]
1  1035545057                   True              True                []

   promotion.premium_ad_page  promotion.urgent  promotion.b2c_ad_page
0                      False             False                  False
1                      False             False                  False

offer_photos
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 0 to 1299
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      1279 non-null   int64
 1   photos  1279 non-null   object
dtypes: int64(1), object(1)
memory usage: 30.0+ KB
None
           id                                             photos
0  1050124482  [{'link': 'https://ireland.apollo.olxcdn.com:4...
1  1035545057  [{'link': 'https://ireland.apollo.olxcdn.com:4...

offer_parameters
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 0 to 1299
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          1279 non-null   int64
 1   params      1279 non-null   object
 2   key_params  1279 non-null   object
dtypes: int64(1), object(2)
memory usage: 40.0+ KB
None
           id                                             params  \
0  1050124482  [{'key': 'price', 'name': 'Cena', 'type': 'pri...
1  1035545057  [{'key': 'price', 'name': 'Cena', 'type': 'pri...

         key_params
0                []
1  [m, price_per_m]

data_location
id                                 1279
isGpsrAvailable                       2
location.city.id                    475
location.city.name                  473
location.city.normalized_name       475
location.city._nodeId                42
location.district.id                141
location.district.name              131
location.district._nodeId            19
location.region.id                   16
location.region.name                 16
location.region.normalized_name      16
location.region._nodeId              12
map.lat                             816
map.lon                             816
map.radius                           13
map.show_detailed                     2
map.zoom                             14
dtype: int64

data_timing
id                     1279
last_refresh_time      1196
created_time           1269
omnibus_pushup_time     598
valid_to_time          1250
dtype: int64

data_category
id                  1279
offer_type             1
category.id           19
category.type          1
category._nodeId      11
dtype: int64

data_business
id                                  1279
business                               2
protect_phone                          2
contact.chat                           1
contact.name                         554
contact.negotiation                    2
contact.phone                          2
shop.subdomain                        16
user.id                              962
user.uuid                            962
user._nodeId                          52
user.about                            25
user.b2c_business_page                 2
user.banner_desktop                   21
user.banner_mobile                    60
user.company_name                     25
user.created                         962
user.is_online                         2
user.last_seen                       960
user.logo_ad_page                     19
user.name                            569
user.other_ads_enabled                 1
user.photo                           144
user.social_network_account_type       1
user.verification.status               1
partner.code                           1
contact.courier                        1
dtype: int64

data_offer
id                                 1279
_nodeId                              52
title                              1241
status                                1
url                                1279
description                        1272
external_url                        241
location.city.id                    475
location.city.name                  473
location.city.normalized_name       475
location.city._nodeId                42
location.district.id                141
location.district.name              131
location.district._nodeId            19
location.region.id                   16
location.region.name                 16
location.region.normalized_name      16
location.region._nodeId              12
dtype: int64

data_promoted
Lista

offer_photos
Lista

offer_parameters
Lista

Delete unnecessary columns:

In [8]:
MAP = {
    'data_location' : 'map.zoom',
    'data_category' : 'offer_type',
    'data_business' : ['user.is_online','contact.courier'],
    'data_offer' : [
        'location.city.id', 'location.city._nodeId', 'location.city.normalized_name', 'location.district.id', 'location.district._nodeId',
        'location.region.id', 'location.region.normalized_name', 'location.region._nodeId'
        ]
}

for name, col in MAP.items():
  dfs_cl[name].drop(col, inplace=True, axis=1)

#print df name and each column with the number of unique values
pc.check_data(dfs_cl)

data_location
id                                 1279
isGpsrAvailable                       2
location.city.id                    475
location.city.name                  473
location.city.normalized_name       475
location.city._nodeId                42
location.district.id                141
location.district.name              131
location.district._nodeId            19
location.region.id                   16
location.region.name                 16
location.region.normalized_name      16
location.region._nodeId              12
map.lat                             816
map.lon                             816
map.radius                           13
map.show_detailed                     2
dtype: int64

data_timing
id                     1279
last_refresh_time      1196
created_time           1269
omnibus_pushup_time     598
valid_to_time          1250
dtype: int64

data_category
id                  1279
category.id           19
category.type          1
category._nodeId      11
dtype: int64

data_business
id                                  1279
business                               2
protect_phone                          2
contact.chat                           1
contact.name                         554
contact.negotiation                    2
contact.phone                          2
shop.subdomain                        16
user.id                              962
user.uuid                            962
user._nodeId                          52
user.about                            25
user.b2c_business_page                 2
user.banner_desktop                   21
user.banner_mobile                    60
user.company_name                     25
user.created                         962
user.last_seen                       960
user.logo_ad_page                     19
user.name                            569
user.other_ads_enabled                 1
user.photo                           144
user.social_network_account_type       1
user.verification.status               1
partner.code                           1
dtype: int64

data_offer
id                        1279
_nodeId                     52
title                     1241
status                       1
url                       1279
description               1272
external_url               241
location.city.name         473
location.district.name     131
location.region.name        16
dtype: int64

data_promoted
Lista

offer_photos
Lista

offer_parameters
Lista

In [9]:
#change index to 'id'
for name, col in dfs_cl.items():
  dfs_cl[name] = dfs_cl[name].set_index('id')

pc.key_info(dfs_cl)

data_location
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 1050124482 to 1053915738
Data columns (total 16 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   isGpsrAvailable                  1279 non-null   bool
 1   location.city.id                 1279 non-null   int64
 2   location.city.name               1279 non-null   object
 3   location.city.normalized_name    1279 non-null   object
 4   location.city._nodeId            52 non-null     object
 5   location.district.id             522 non-null    float64
 6   location.district.name           522 non-null    object
 7   location.district._nodeId        19 non-null     object
 8   location.region.id               1279 non-null   int64
 9   location.region.name             1279 non-null   object
 10  location.region.normalized_name  1279 non-null   object
 11  location.region._nodeId          52 non-null     object
 12  map.lat                          1279 non-null   float64
 13  map.lon                          1279 non-null   float64
 14  map.radius                       1279 non-null   int64
 15  map.show_detailed                1279 non-null   bool
dtypes: bool(2), float64(3), int64(3), object(8)
memory usage: 152.4+ KB
None
            isGpsrAvailable  location.city.id location.city.name  \
id
1050124482            False             17871           Warszawa
1035545057            False            102641          Niesłabin

           location.city.normalized_name location.city._nodeId  \
id
1050124482                      warszawa      Y2l0eToxNzg3MQ==
1035545057                     nieslabin      Y2l0eToxMDI2NDE=

            location.district.id location.district.name  \
id
1050124482                 353.0                Mokotów
1035545057                   NaN                    NaN

           location.district._nodeId  location.region.id location.region.name  \
id
1050124482          ZGlzdHJpY3Q6MzUz                   2          Mazowieckie
1035545057                       NaN                   1        Wielkopolskie

           location.region.normalized_name location.region._nodeId   map.lat  \
id
1050124482                     mazowieckie            cmVnaW9uOjI=  52.19282
1035545057                   wielkopolskie            cmVnaW9uOjE=  52.16511

             map.lon  map.radius  map.show_detailed
id
1050124482  21.03232           7              False
1035545057  17.01334           0               True

data_timing
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 1050124482 to 1053915738
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   last_refresh_time    1279 non-null   object
 1   created_time         1279 non-null   object
 2   omnibus_pushup_time  622 non-null    object
 3   valid_to_time        1279 non-null   object
dtypes: object(4)
memory usage: 50.0+ KB
None
                    last_refresh_time               created_time  \
id
1050124482  2026-02-06T06:38:01+01:00  2026-01-18T11:16:21+01:00
1035545057  2026-02-06T16:33:40+01:00  2025-10-30T18:18:37+01:00

                  omnibus_pushup_time              valid_to_time
id
1050124482  2026-02-06T06:38:01+01:00  2026-02-17T11:16:21+01:00
1035545057  2026-02-06T16:33:40+01:00  2026-02-09T16:37:59+01:00

data_category
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 1050124482 to 1053915738
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   category.id       1279 non-null   int64
 1   category.type     1279 non-null   object
 2   category._nodeId  52 non-null     object
dtypes: int64(1), object(2)
memory usage: 40.0+ KB
None
            category.id category.type  category._nodeId
id
1050124482           11   real_estate  Y2F0ZWdvcnk6MTE=
1035545057           18   real_estate  Y2F0ZWdvcnk6MTg=

data_business
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 1050124482 to 1053915738
Data columns (total 24 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   business                          1279 non-null   bool
 1   protect_phone                     1099 non-null   object
 2   contact.chat                      1279 non-null   bool
 3   contact.name                      1279 non-null   object
 4   contact.negotiation               1279 non-null   bool
 5   contact.phone                     1279 non-null   bool
 6   shop.subdomain                    49 non-null     object
 7   user.id                           1279 non-null   int64
 8   user.uuid                         1279 non-null   object
 9   user._nodeId                      52 non-null     object
 10  user.about                        1279 non-null   object
 11  user.b2c_business_page            1279 non-null   bool
 12  user.banner_desktop               1279 non-null   object
 13  user.banner_mobile                1279 non-null   object
 14  user.company_name                 1279 non-null   object
 15  user.created                      1279 non-null   object
 16  user.last_seen                    1279 non-null   object
 17  user.logo_ad_page                 41 non-null     object
 18  user.name                         1279 non-null   object
 19  user.other_ads_enabled            1279 non-null   bool
 20  user.photo                        147 non-null    object
 21  user.social_network_account_type  289 non-null    object
 22  user.verification.status          52 non-null     object
 23  partner.code                      241 non-null    object
dtypes: bool(6), int64(1), object(17)
memory usage: 197.3+ KB
None
            business protect_phone  contact.chat      contact.name  \
id
1050124482     False          True          True            Wojtek
1035545057      True          True          True  HOME4ME Sp z o o

            contact.negotiation  contact.phone shop.subdomain     user.id  \
id
1050124482                False           True           None  1497179207
1035545057                False           True           None    21117567

                                       user.uuid  \
id
1050124482  9faf5def-6fce-48f9-b358-6f7166b38c43
1035545057  ffce0e06-25f9-4d4f-9a59-ae1477b57dce

                                        user._nodeId  ... user.company_name  \
id                                                    ...
1050124482  d5dcf823aaf5a1d5dc06c9730b9bf65730527b3e  ...
1035545057  fa11fa49d1142c6ac27a02af2a8dbabc0afd639c  ...

                         user.created             user.last_seen  \
id
1050124482  2023-03-28T07:27:25+02:00  2026-02-05T20:09:59+01:00
1035545057  2014-05-23T01:05:01+02:00  2026-02-08T00:13:31+01:00

           user.logo_ad_page         user.name user.other_ads_enabled  \
id
1050124482              None           woj1492                   True
1035545057              None  HOME4ME Sp z o o                   True

           user.photo user.social_network_account_type  \
id
1050124482       None                             None
1035545057       None                             None

           user.verification.status  partner.code
id
1050124482                     none           NaN
1035545057                     none     otodom_pl

[2 rows x 24 columns]

data_offer
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 1050124482 to 1053915738
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   _nodeId                 52 non-null     object
 1   title                   1279 non-null   object
 2   status                  1279 non-null   object
 3   url                     1279 non-null   object
 4   description             1279 non-null   object
 5   external_url            241 non-null    object
 6   location.city.name      1279 non-null   object
 7   location.district.name  522 non-null    object
 8   location.region.name    1279 non-null   object
dtypes: object(9)
memory usage: 99.9+ KB
None
                                     _nodeId  \
id
1050124482  bGVnYWN5QWR2ZXJ0OjEwNTAxMjQ0ODI=
1035545057  bGVnYWN5QWR2ZXJ0OjEwMzU1NDUwNTc=

                                                        title  status  \
id
1050124482  Komfortowy pokój z balkonem, Mokotów, obok met...  active
1035545057  Piękna rezydencja przy lesie w stylu Vastu w s...  active

                                                          url  \
id
1050124482  https://www.olx.pl/d/oferta/komfortowy-pokoj-z...
1035545057  https://www.olx.pl/d/oferta/piekna-rezydencja-...

                                                  description  \
id
1050124482  English description bellow!<br />\n<br />\nDo ...
1035545057  <p></p><p>Nieruchomość położona jest pośród pó...

                                                 external_url  \
id
1050124482                                               None
1035545057  https://www.otodom.pl/pl/oferta/piekna-rezyden...

           location.city.name location.district.name location.region.name
id
1050124482           Warszawa                Mokotów          Mazowieckie
1035545057          Niesłabin                    NaN        Wielkopolskie

data_promoted
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 1050124482 to 1053915738
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   promotion.highlighted      1279 non-null   bool
 1   promotion.top_ad           1279 non-null   bool
 2   promotion.options          1279 non-null   object
 3   promotion.premium_ad_page  1279 non-null   bool
 4   promotion.urgent           1279 non-null   bool
 5   promotion.b2c_ad_page      1279 non-null   bool
dtypes: bool(5), object(1)
memory usage: 26.2+ KB
None
            promotion.highlighted  promotion.top_ad promotion.options  \
id
1050124482                   True              True  [bundle_optimum]
1035545057                   True              True                []

            promotion.premium_ad_page  promotion.urgent  promotion.b2c_ad_page
id
1050124482                      False             False                  False
1035545057                      False             False                  False

offer_photos
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 1050124482 to 1053915738
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   photos  1279 non-null   object
dtypes: object(1)
memory usage: 20.0+ KB
None
                                                       photos
id
1050124482  [{'link': 'https://ireland.apollo.olxcdn.com:4...
1035545057  [{'link': 'https://ireland.apollo.olxcdn.com:4...

offer_parameters
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 1050124482 to 1053915738
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   params      1279 non-null   object
 1   key_params  1279 non-null   object
dtypes: object(2)
memory usage: 30.0+ KB
None
                                                       params  \
id
1050124482  [{'key': 'price', 'name': 'Cena', 'type': 'pri...
1035545057  [{'key': 'price', 'name': 'Cena', 'type': 'pri...

                  key_params
id
1050124482                []
1035545057  [m, price_per_m]

# View each df, check dtype, NaN values, etc

In [46]:
dfs_cl.keys()

dict_keys(['data_location', 'data_timing', 'data_category', 'data_business', 'data_offer', 'data_promoted', 'offer_photos', 'offer_parameters'])

In [82]:
dfs_cl['data_business']['user created']

id
1053259578    2011-12-08T18:02:37+01:00
1053647970    2014-05-23T01:05:01+02:00
1053177976    2014-03-03T14:23:55+01:00
1050662711    2012-09-04T18:09:32+02:00
1023797479    2014-05-23T01:05:01+02:00
                        ...
1039680054    2016-06-11T12:49:54+02:00
1037078764    2014-10-14T17:09:54+02:00
926801959     2023-10-28T13:24:20+02:00
1043246499    2016-02-07T12:54:29+01:00
1053839475    2013-12-15T17:49:09+01:00
Name: user created, Length: 1175, dtype: object

In [10]:
#unifying column names
COL_MAP = {
    'data_location' : {
        name : name.strip().replace('location.', '').replace('.', ' ')
        if 'location.' in name else
        name.strip().replace('.', ' ')
        for name in dfs_cl['data_location'].columns
        },
    'data_timing' : {name : name.strip().replace('_', ' ') for name in dfs_cl['data_timing'].columns},
    'data_category' : {
        name : name.strip().replace('category.', '')
        if '.id' not in name else
        name.strip().replace('.', ' ')
        for name in dfs_cl['data_category']
        },
    'data_business' : {name : name.strip().replace('.', ' ') for name in dfs_cl['data_business'].columns},
    'data_offer' : {name : name.strip().replace('location.', '').replace('.', ' ') for name in dfs_cl['data_offer'].columns},
    'data_promoted' : {name : name.strip().replace('promotion.', '') for name in dfs_cl['data_promoted'].columns}
}

for name, col in COL_MAP.items():
  dfs_cl[name].rename(columns=col, inplace=True)

pc.key_info(dfs_cl)

data_location
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 1050124482 to 1053915738
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   isGpsrAvailable         1279 non-null   bool
 1   city id                 1279 non-null   int64
 2   city name               1279 non-null   object
 3   city normalized_name    1279 non-null   object
 4   city _nodeId            52 non-null     object
 5   district id             522 non-null    float64
 6   district name           522 non-null    object
 7   district _nodeId        19 non-null     object
 8   region id               1279 non-null   int64
 9   region name             1279 non-null   object
 10  region normalized_name  1279 non-null   object
 11  region _nodeId          52 non-null     object
 12  map lat                 1279 non-null   float64
 13  map lon                 1279 non-null   float64
 14  map radius              1279 non-null   int64
 15  map show_detailed       1279 non-null   bool
dtypes: bool(2), float64(3), int64(3), object(8)
memory usage: 152.4+ KB
None
            isGpsrAvailable  city id  city name city normalized_name  \
id
1050124482            False    17871   Warszawa             warszawa
1035545057            False   102641  Niesłabin            nieslabin

                city _nodeId  district id district name  district _nodeId  \
id
1050124482  Y2l0eToxNzg3MQ==        353.0       Mokotów  ZGlzdHJpY3Q6MzUz
1035545057  Y2l0eToxMDI2NDE=          NaN           NaN               NaN

            region id    region name region normalized_name region _nodeId  \
id
1050124482          2    Mazowieckie            mazowieckie   cmVnaW9uOjI=
1035545057          1  Wielkopolskie          wielkopolskie   cmVnaW9uOjE=

             map lat   map lon  map radius  map show_detailed
id
1050124482  52.19282  21.03232           7              False
1035545057  52.16511  17.01334           0               True

data_timing
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 1050124482 to 1053915738
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   last refresh time    1279 non-null   object
 1   created time         1279 non-null   object
 2   omnibus pushup time  622 non-null    object
 3   valid to time        1279 non-null   object
dtypes: object(4)
memory usage: 50.0+ KB
None
                    last refresh time               created time  \
id
1050124482  2026-02-06T06:38:01+01:00  2026-01-18T11:16:21+01:00
1035545057  2026-02-06T16:33:40+01:00  2025-10-30T18:18:37+01:00

                  omnibus pushup time              valid to time
id
1050124482  2026-02-06T06:38:01+01:00  2026-02-17T11:16:21+01:00
1035545057  2026-02-06T16:33:40+01:00  2026-02-09T16:37:59+01:00

data_category
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 1050124482 to 1053915738
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   category id  1279 non-null   int64
 1   type         1279 non-null   object
 2   _nodeId      52 non-null     object
dtypes: int64(1), object(2)
memory usage: 40.0+ KB
None
            category id         type           _nodeId
id
1050124482           11  real_estate  Y2F0ZWdvcnk6MTE=
1035545057           18  real_estate  Y2F0ZWdvcnk6MTg=

data_business
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 1050124482 to 1053915738
Data columns (total 24 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   business                          1279 non-null   bool
 1   protect_phone                     1099 non-null   object
 2   contact chat                      1279 non-null   bool
 3   contact name                      1279 non-null   object
 4   contact negotiation               1279 non-null   bool
 5   contact phone                     1279 non-null   bool
 6   shop subdomain                    49 non-null     object
 7   user id                           1279 non-null   int64
 8   user uuid                         1279 non-null   object
 9   user _nodeId                      52 non-null     object
 10  user about                        1279 non-null   object
 11  user b2c_business_page            1279 non-null   bool
 12  user banner_desktop               1279 non-null   object
 13  user banner_mobile                1279 non-null   object
 14  user company_name                 1279 non-null   object
 15  user created                      1279 non-null   object
 16  user last_seen                    1279 non-null   object
 17  user logo_ad_page                 41 non-null     object
 18  user name                         1279 non-null   object
 19  user other_ads_enabled            1279 non-null   bool
 20  user photo                        147 non-null    object
 21  user social_network_account_type  289 non-null    object
 22  user verification status          52 non-null     object
 23  partner code                      241 non-null    object
dtypes: bool(6), int64(1), object(17)
memory usage: 197.3+ KB
None
            business protect_phone  contact chat      contact name  \
id
1050124482     False          True          True            Wojtek
1035545057      True          True          True  HOME4ME Sp z o o

            contact negotiation  contact phone shop subdomain     user id  \
id
1050124482                False           True           None  1497179207
1035545057                False           True           None    21117567

                                       user uuid  \
id
1050124482  9faf5def-6fce-48f9-b358-6f7166b38c43
1035545057  ffce0e06-25f9-4d4f-9a59-ae1477b57dce

                                        user _nodeId  ... user company_name  \
id                                                    ...
1050124482  d5dcf823aaf5a1d5dc06c9730b9bf65730527b3e  ...
1035545057  fa11fa49d1142c6ac27a02af2a8dbabc0afd639c  ...

                         user created             user last_seen  \
id
1050124482  2023-03-28T07:27:25+02:00  2026-02-05T20:09:59+01:00
1035545057  2014-05-23T01:05:01+02:00  2026-02-08T00:13:31+01:00

           user logo_ad_page         user name user other_ads_enabled  \
id
1050124482              None           woj1492                   True
1035545057              None  HOME4ME Sp z o o                   True

           user photo user social_network_account_type  \
id
1050124482       None                             None
1035545057       None                             None

           user verification status  partner code
id
1050124482                     none           NaN
1035545057                     none     otodom_pl

[2 rows x 24 columns]

data_offer
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 1050124482 to 1053915738
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   _nodeId        52 non-null     object
 1   title          1279 non-null   object
 2   status         1279 non-null   object
 3   url            1279 non-null   object
 4   description    1279 non-null   object
 5   external_url   241 non-null    object
 6   city name      1279 non-null   object
 7   district name  522 non-null    object
 8   region name    1279 non-null   object
dtypes: object(9)
memory usage: 99.9+ KB
None
                                     _nodeId  \
id
1050124482  bGVnYWN5QWR2ZXJ0OjEwNTAxMjQ0ODI=
1035545057  bGVnYWN5QWR2ZXJ0OjEwMzU1NDUwNTc=

                                                        title  status  \
id
1050124482  Komfortowy pokój z balkonem, Mokotów, obok met...  active
1035545057  Piękna rezydencja przy lesie w stylu Vastu w s...  active

                                                          url  \
id
1050124482  https://www.olx.pl/d/oferta/komfortowy-pokoj-z...
1035545057  https://www.olx.pl/d/oferta/piekna-rezydencja-...

                                                  description  \
id
1050124482  English description bellow!<br />\n<br />\nDo ...
1035545057  <p></p><p>Nieruchomość położona jest pośród pó...

                                                 external_url  city name  \
id
1050124482                                               None   Warszawa
1035545057  https://www.otodom.pl/pl/oferta/piekna-rezyden...  Niesłabin

           district name    region name
id
1050124482       Mokotów    Mazowieckie
1035545057           NaN  Wielkopolskie

data_promoted
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 1050124482 to 1053915738
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   highlighted      1279 non-null   bool
 1   top_ad           1279 non-null   bool
 2   options          1279 non-null   object
 3   premium_ad_page  1279 non-null   bool
 4   urgent           1279 non-null   bool
 5   b2c_ad_page      1279 non-null   bool
dtypes: bool(5), object(1)
memory usage: 26.2+ KB
None
            highlighted  top_ad           options  premium_ad_page  urgent  \
id
1050124482         True    True  [bundle_optimum]            False   False
1035545057         True    True                []            False   False

            b2c_ad_page
id
1050124482        False
1035545057        False

offer_photos
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 1050124482 to 1053915738
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   photos  1279 non-null   object
dtypes: object(1)
memory usage: 20.0+ KB
None
                                                       photos
id
1050124482  [{'link': 'https://ireland.apollo.olxcdn.com:4...
1035545057  [{'link': 'https://ireland.apollo.olxcdn.com:4...

offer_parameters
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 1050124482 to 1053915738
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   params      1279 non-null   object
 1   key_params  1279 non-null   object
dtypes: object(2)
memory usage: 30.0+ KB
None
                                                       params  \
id
1050124482  [{'key': 'price', 'name': 'Cena', 'type': 'pri...
1035545057  [{'key': 'price', 'name': 'Cena', 'type': 'pri...

                  key_params
id
1050124482                []
1035545057  [m, price_per_m]

In [65]:
dfs_cl.keys()

dict_keys(['data_location', 'data_timing', 'data_category', 'data_business', 'data_offer', 'data_promoted', 'offer_photos', 'offer_parameters'])

In [93]:
dfs_cl['data_business'].dtypes

business                              bool
protect_phone                       object
contact chat                          bool
contact name                        object
contact negotiation                   bool
contact phone                         bool
shop subdomain                      object
user id                              int64
user uuid                           object
user _nodeId                        object
user about                          object
user b2c_business_page                bool
user banner_desktop                 object
user banner_mobile                  object
user company_name                   object
user created                        object
user last_seen                      object
user logo_ad_page                   object
user name                           object
user other_ads_enabled                bool
user photo                          object
user social_network_account_type    object
user verification status            object
partner code                        object
dtype: object

In [11]:
#normalizing dtypes in DataFrames
from pandas.api.types import is_datetime64_any_dtype, is_object_dtype, is_bool_dtype, is_numeric_dtype

DTYPE_MAP = {
    'data_location' : {
        'isGpsrAvailable' : 'bool',
        'city id' : 'object',
        'city name' : 'object',
        'city normalized_name' : 'object',
        'city _nodeId' : 'object',
        'region id' : 'object',
        'region name' : 'object',
        'region normalized_name' : 'object',
        'region _nodeId' : 'object',
        'map lat' : 'float',
        'map lon' : 'float',
        'map radius' : 'int',
        'map show_detailed' : 'bool',
        'district id' : 'object',
        'district name' : 'object',
        'district _nodeId' : 'object'
    },
    'data_timing' : {
        'last refresh time' : 'datetime',
        'created time' : 'datetime',
        'omnibus pushup time' : 'datetime',
        'valid to time' : 'datetime'
    },
    'data_category' : {
        'category id' : 'category',
        'type' : 'category',
        '_nodeId' : 'object'
    },
    'data_business' : {
        'business' : 'bool',
        'protect_phone' : 'bool',
        'contact chat' : 'bool',
        'contact name' : 'object',
        'contact negotiation' : 'bool',
        'contact phone' : 'bool',
        'shop subdomain' : 'object',
        'user id' : 'object',
        'user uuid' : 'object',
        'user _nodeId' : 'object',
        'user about' : 'object',
        'user b2c_business_page' : 'bool',
        'user banner_desktop' : 'object',
        'user banner_mobile' : 'object',
        'user company_name' : 'object',
        'user created' : 'datetime',
        'user last_seen' : 'datetime',
        'user logo_ad_page' : 'object',
        'user name' : 'object',
        'user other_ads_enabled' : 'bool',
        'user photo' : 'object',
        'user social_network_account_type' : 'category',
        'user verification status' : 'object',
        'partner code' : 'object'
    },
    'data_offer' : {
        '_nodeId' : 'object',
        'title' : 'object',
        'status' : 'category',
        'url' : 'object',
        'description' : 'object',
        'external_url' : 'object',
        'city name' : 'object',
        'region name' :'object',
        'district name' : 'object'

    },
    'data_promoted' : {
        'highlighted' : 'bool',
        'top_ad' : 'bool',
        'options' : 'object',
        'premium_ad_page' : 'bool',
        'urgent' : 'bool',
        'b2c_ad_page' : 'bool'
    }
}

for name, df in DTYPE_MAP.items():
  if name not in dfs_cl:
    continue

  for col_name, dtype in df.items():
    if col_name not in dfs_cl[name].columns:
            continue

    if dtype == 'datetime' and not is_datetime64_any_dtype(dfs_cl[name][col_name]):
      dfs_cl[name][col_name] = pd.to_datetime(dfs_cl[name][col_name], utc=True, errors="coerce").dt.tz_convert('Europe/Warsaw')

    elif dtype == 'object' and not is_object_dtype(dfs_cl[name][col_name]):
      dfs_cl[name][col_name] = dfs_cl[name][col_name].astype('object')

    elif dtype == 'bool' and not is_bool_dtype(dfs_cl[name][col_name]):
      dfs_cl[name][col_name] = dfs_cl[name][col_name].astype('boolean')

    elif dtype in ('float', 'int') and not is_numeric_dtype(dfs_cl[name][col_name]):
      dfs_cl[name][col_name] = pd.to_numeric(dfs_cl[name][col_name], errors='coerce')

    elif dtype == 'category':
      dfs_cl[name][col_name] = dfs_cl[name][col_name].astype('category')

pc.key_info(dfs_cl)

data_location
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 1050124482 to 1053915738
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   isGpsrAvailable         1279 non-null   bool
 1   city id                 1279 non-null   object
 2   city name               1279 non-null   object
 3   city normalized_name    1279 non-null   object
 4   city _nodeId            52 non-null     object
 5   district id             522 non-null    object
 6   district name           522 non-null    object
 7   district _nodeId        19 non-null     object
 8   region id               1279 non-null   object
 9   region name             1279 non-null   object
 10  region normalized_name  1279 non-null   object
 11  region _nodeId          52 non-null     object
 12  map lat                 1279 non-null   float64
 13  map lon                 1279 non-null   float64
 14  map radius              1279 non-null   int64
 15  map show_detailed       1279 non-null   bool
dtypes: bool(2), float64(2), int64(1), object(11)
memory usage: 152.4+ KB
None
            isGpsrAvailable city id  city name city normalized_name  \
id
1050124482            False   17871   Warszawa             warszawa
1035545057            False  102641  Niesłabin            nieslabin

                city _nodeId district id district name  district _nodeId  \
id
1050124482  Y2l0eToxNzg3MQ==       353.0       Mokotów  ZGlzdHJpY3Q6MzUz
1035545057  Y2l0eToxMDI2NDE=         NaN           NaN               NaN

           region id    region name region normalized_name region _nodeId  \
id
1050124482         2    Mazowieckie            mazowieckie   cmVnaW9uOjI=
1035545057         1  Wielkopolskie          wielkopolskie   cmVnaW9uOjE=

             map lat   map lon  map radius  map show_detailed
id
1050124482  52.19282  21.03232           7              False
1035545057  52.16511  17.01334           0               True

data_timing
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 1050124482 to 1053915738
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   last refresh time    1279 non-null   datetime64[ns, Europe/Warsaw]
 1   created time         1279 non-null   datetime64[ns, Europe/Warsaw]
 2   omnibus pushup time  622 non-null    datetime64[ns, Europe/Warsaw]
 3   valid to time        1279 non-null   datetime64[ns, Europe/Warsaw]
dtypes: datetime64[ns, Europe/Warsaw](4)
memory usage: 50.0 KB
None
                   last refresh time              created time  \
id
1050124482 2026-02-06 06:38:01+01:00 2026-01-18 11:16:21+01:00
1035545057 2026-02-06 16:33:40+01:00 2025-10-30 18:18:37+01:00

                 omnibus pushup time             valid to time
id
1050124482 2026-02-06 06:38:01+01:00 2026-02-17 11:16:21+01:00
1035545057 2026-02-06 16:33:40+01:00 2026-02-09 16:37:59+01:00

data_category
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 1050124482 to 1053915738
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   category id  1279 non-null   category
 1   type         1279 non-null   category
 2   _nodeId      52 non-null     object
dtypes: category(2), object(1)
memory usage: 23.3+ KB
None
           category id         type           _nodeId
id
1050124482          11  real_estate  Y2F0ZWdvcnk6MTE=
1035545057          18  real_estate  Y2F0ZWdvcnk6MTg=

data_business
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 1050124482 to 1053915738
Data columns (total 24 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   business                          1279 non-null   bool
 1   protect_phone                     1099 non-null   boolean
 2   contact chat                      1279 non-null   bool
 3   contact name                      1279 non-null   object
 4   contact negotiation               1279 non-null   bool
 5   contact phone                     1279 non-null   bool
 6   shop subdomain                    49 non-null     object
 7   user id                           1279 non-null   object
 8   user uuid                         1279 non-null   object
 9   user _nodeId                      52 non-null     object
 10  user about                        1279 non-null   object
 11  user b2c_business_page            1279 non-null   bool
 12  user banner_desktop               1279 non-null   object
 13  user banner_mobile                1279 non-null   object
 14  user company_name                 1279 non-null   object
 15  user created                      1279 non-null   datetime64[ns, Europe/Warsaw]
 16  user last_seen                    1279 non-null   datetime64[ns, Europe/Warsaw]
 17  user logo_ad_page                 41 non-null     object
 18  user name                         1279 non-null   object
 19  user other_ads_enabled            1279 non-null   bool
 20  user photo                        147 non-null    object
 21  user social_network_account_type  289 non-null    category
 22  user verification status          52 non-null     object
 23  partner code                      241 non-null    object
dtypes: bool(6), boolean(1), category(1), datetime64[ns, Europe/Warsaw](2), object(14)
memory usage: 181.2+ KB
None
            business  protect_phone  contact chat      contact name  \
id
1050124482     False           True          True            Wojtek
1035545057      True           True          True  HOME4ME Sp z o o

            contact negotiation  contact phone shop subdomain     user id  \
id
1050124482                False           True           None  1497179207
1035545057                False           True           None    21117567

                                       user uuid  \
id
1050124482  9faf5def-6fce-48f9-b358-6f7166b38c43
1035545057  ffce0e06-25f9-4d4f-9a59-ae1477b57dce

                                        user _nodeId  ... user company_name  \
id                                                    ...
1050124482  d5dcf823aaf5a1d5dc06c9730b9bf65730527b3e  ...
1035545057  fa11fa49d1142c6ac27a02af2a8dbabc0afd639c  ...

                        user created            user last_seen  \
id
1050124482 2023-03-28 07:27:25+02:00 2026-02-05 20:09:59+01:00
1035545057 2014-05-23 01:05:01+02:00 2026-02-08 00:13:31+01:00

           user logo_ad_page         user name user other_ads_enabled  \
id
1050124482              None           woj1492                   True
1035545057              None  HOME4ME Sp z o o                   True

           user photo user social_network_account_type  \
id
1050124482       None                              NaN
1035545057       None                              NaN

           user verification status  partner code
id
1050124482                     none           NaN
1035545057                     none     otodom_pl

[2 rows x 24 columns]

data_offer
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 1050124482 to 1053915738
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   _nodeId        52 non-null     object
 1   title          1279 non-null   object
 2   status         1279 non-null   category
 3   url            1279 non-null   object
 4   description    1279 non-null   object
 5   external_url   241 non-null    object
 6   city name      1279 non-null   object
 7   district name  522 non-null    object
 8   region name    1279 non-null   object
dtypes: category(1), object(8)
memory usage: 91.3+ KB
None
                                     _nodeId  \
id
1050124482  bGVnYWN5QWR2ZXJ0OjEwNTAxMjQ0ODI=
1035545057  bGVnYWN5QWR2ZXJ0OjEwMzU1NDUwNTc=

                                                        title  status  \
id
1050124482  Komfortowy pokój z balkonem, Mokotów, obok met...  active
1035545057  Piękna rezydencja przy lesie w stylu Vastu w s...  active

                                                          url  \
id
1050124482  https://www.olx.pl/d/oferta/komfortowy-pokoj-z...
1035545057  https://www.olx.pl/d/oferta/piekna-rezydencja-...

                                                  description  \
id
1050124482  English description bellow!<br />\n<br />\nDo ...
1035545057  <p></p><p>Nieruchomość położona jest pośród pó...

                                                 external_url  city name  \
id
1050124482                                               None   Warszawa
1035545057  https://www.otodom.pl/pl/oferta/piekna-rezyden...  Niesłabin

           district name    region name
id
1050124482       Mokotów    Mazowieckie
1035545057           NaN  Wielkopolskie

data_promoted
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 1050124482 to 1053915738
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   highlighted      1279 non-null   bool
 1   top_ad           1279 non-null   bool
 2   options          1279 non-null   object
 3   premium_ad_page  1279 non-null   bool
 4   urgent           1279 non-null   bool
 5   b2c_ad_page      1279 non-null   bool
dtypes: bool(5), object(1)
memory usage: 26.2+ KB
None
            highlighted  top_ad           options  premium_ad_page  urgent  \
id
1050124482         True    True  [bundle_optimum]            False   False
1035545057         True    True                []            False   False

            b2c_ad_page
id
1050124482        False
1035545057        False

offer_photos
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 1050124482 to 1053915738
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   photos  1279 non-null   object
dtypes: object(1)
memory usage: 20.0+ KB
None
                                                       photos
id
1050124482  [{'link': 'https://ireland.apollo.olxcdn.com:4...
1035545057  [{'link': 'https://ireland.apollo.olxcdn.com:4...

offer_parameters
<class 'pandas.core.frame.DataFrame'>
Index: 1279 entries, 1050124482 to 1053915738
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   params      1279 non-null   object
 1   key_params  1279 non-null   object
dtypes: object(2)
memory usage: 30.0+ KB
None
                                                       params  \
id
1050124482  [{'key': 'price', 'name': 'Cena', 'type': 'pri...
1035545057  [{'key': 'price', 'name': 'Cena', 'type': 'pri...

                  key_params
id
1050124482                []
1035545057  [m, price_per_m]

In [12]:
#drop rows where is no url
dfs_cl['data_offer'].dropna(subset='url', inplace=True)